version: '3.4'

services:
  mongodbtest:
    image: mongodbtest
    build:
      context: .
      dockerfile: MongoDbTest.Api/Dockerfile
    ports:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
